name = "Chuffed"
uuid = "a105ee56-0da9-4c5a-a151-cc7e299d31db"
authors = ["Thibaut Cuvelier <cuvelier.thibaut@gmail.com>"]
repo = "https://github.com/JuliaConstraints/Chuffed.jl"
version = "0.3.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
ConstraintProgrammingExtensions = "b65d079e-ed98-51d9-b0db-edee61a5c5f8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Chuffed_jll = "77125aae-c893-5498-99e3-e30470bfa328"

[compat]
julia = "1.6"
MathOptInterface = "1"
ConstraintProgrammingExtensions = "0.7"
Chuffed_jll = "=0.10.4, =0.13.2"
