name = "Chuffed"
uuid = "a105ee56-0da9-4c5a-a151-cc7e299d31db"
authors = ["Thibaut Cuvelier <cuvelier.thibaut@gmail.com>"]
repo = "https://github.com/dourouc05/Chuffed.jl"
version = "0.1.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
ConstraintProgrammingExtensions = "b65d079e-ed98-51d9-b0db-edee61a5c5f8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "^1.5"
MathOptInterface = "^0.9"
ConstraintProgrammingExtensions = "^0.4"
